[tool.poetry]
name = "resume"
version = "0.1.0"
description = "rendercv resume"
authors = ["adenc@uchicago.edu"]
packages = []

[tool.poetry.dependencies]
python = "^3.12"
rendercv = "^2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

